"""rework2

Revision ID: 6acba2cb871b
Revises: 57e41c67ff29
Create Date: 2025-12-20 23:32:11.807492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6acba2cb871b'
down_revision = '57e41c67ff29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ion_redox_reaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'ion_redox_result', ['result_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ion_redox_reaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('result_id')

    # ### end Alembic commands ###
