"""Initial migration

Revision ID: cecb28d4f974
Revises: 
Create Date: 2025-12-18 16:52:18.416288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecb28d4f974'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('electrode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sign', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sign')
    )
    op.create_table('ion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bath',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('anode_id', sa.Integer(), nullable=False),
    sa.Column('cathode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anode_id'], ['electrode.id'], ),
    sa.ForeignKeyConstraint(['cathode_id'], ['electrode.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('compound_element_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=True),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('element_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compound.id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['element.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ion_element',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ion_id', sa.Integer(), nullable=True),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('element_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['element.id'], ),
    sa.ForeignKeyConstraint(['ion_id'], ['ion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ion_redox_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ion_id', sa.Integer(), nullable=True),
    sa.Column('potential', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ion_id'], ['ion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ionic_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ion_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ion_id'], ['ion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solvent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compound.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electrode_overpotential_effect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electrode_id', sa.Integer(), nullable=True),
    sa.Column('reaction_id', sa.Integer(), nullable=False),
    sa.Column('overpotential_effect', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['electrode_id'], ['electrode.id'], ),
    sa.ForeignKeyConstraint(['reaction_id'], ['ion_redox_reaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ion_redox_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('redox_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['redox_id'], ['ion_redox_reaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ionic_compound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('anion_component_id', sa.Integer(), nullable=False),
    sa.Column('cation_component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anion_component_id'], ['ionic_component.id'], ),
    sa.ForeignKeyConstraint(['cation_component_id'], ['ionic_component.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bath_solute_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bath_id', sa.Integer(), nullable=True),
    sa.Column('ionic_compound_id', sa.Integer(), nullable=False),
    sa.Column('concentration', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bath_id'], ['bath.id'], ),
    sa.ForeignKeyConstraint(['ionic_compound_id'], ['ionic_compound.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compound_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compound.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['ion_redox_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('element_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['element.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['ion_redox_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ion_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('ion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ion_id'], ['ion.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['ion_redox_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solubility',
    sa.Column('ionic_compound_id', sa.Integer(), nullable=False),
    sa.Column('solvent_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ionic_compound_id'], ['ionic_compound.id'], ),
    sa.ForeignKeyConstraint(['solvent_id'], ['solvent.id'], ),
    sa.PrimaryKeyConstraint('ionic_compound_id', 'solvent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solubility')
    op.drop_table('ion_result')
    op.drop_table('element_result')
    op.drop_table('compound_result')
    op.drop_table('bath_solute_component')
    op.drop_table('ionic_compound')
    op.drop_table('ion_redox_result')
    op.drop_table('electrode_overpotential_effect')
    op.drop_table('solvent')
    op.drop_table('ionic_component')
    op.drop_table('ion_redox_reaction')
    op.drop_table('ion_element')
    op.drop_table('compound_element_component')
    op.drop_table('bath')
    op.drop_table('ion')
    op.drop_table('element')
    op.drop_table('electrode')
    op.drop_table('compound')
    # ### end Alembic commands ###
